### ISSUE TITLE
SSID with a white space in wifi.cfg file is not working

### ISSUE THREAD

**Issue by benitoss** [hash6iron/powadcr#16]
If the configured SSID (on the wifi.cfg file) contains a white space,  WiFi connection never happens.
But it works if in the powadcr.cpp, I substitute the line
**strcpy(ssid, (sdm.getValueOfParam(CFGWIFI[1].cfgLine,"ssid")).c_str());**
by
**strcpy(ssid, "My SSID");**

So the error is inside the library when it gets the parameter value in the **getValueOfParam** function.

Thanks

**Comment by hash6iron** [comment]
Hi benitoss. 

Sorry. I try to solve in the next rolling release.
Thxs!

**Comment by hash6iron** [comment]
Try release #241107-1421
Thxs!

**Comment by benitoss** [comment]
Solucionado. Gracias !!!!
