### ISSUE TITLE
En el teclado de Search hay teclas que no se corresponden con el caracter que se obtiene al pulsarlas

### ISSUE THREAD

**Issue by TxarlyM** [hash6iron/powadcr#20]
En el teclado de Search hay teclas que no se corresponden con el caracter que se obtiene al pulsarlas.

 - Al pulsar + se obtiene es <
 - Al pulsar * se obtiene %
 - Al pulsar / se obtiewne &
 - Al pulsar Ñ se obtiene +
 
El resto de las teclas están correctamente configuradas.

**Comment by hash6iron** [comment]
El bug ha sido corregido.
- La Ñ se ha eliminado por incompatibilidad con la pantalla
- Se han añadido mas teclas
- Se han comprobado todas las teclasy el caracter que genera.

Probar la rama test_20241112-0908 para verificar las correcciones.
- Actualizar firmware y HMI
