### ISSUE TITLE
Serial logs.

### ISSUE THREAD

**Issue by jgauchia** [hash6iron/powadcr#29]
All output logs are send with _log_ and  _logln_ function

https://github.com/hash6iron/powadcr/blob/main/src/globales.h#L400  
  
Since the output is made through the same port used by the HMI screen when starting or depending on the logs that are displayed, they can interfere with the communication

For the logs it would be good to use _log_v_ , _log_i_ or _log_e_ which go together with the buildflag DEBUG_CORE_LEVEL and it is possible to deactivate them with level 0

**Comment by jgauchia** [comment]
With PR #28  HMI and USB ports will be separated.

**Comment by hash6iron** [comment]
Ok
